name: C/C++ CI

on:
  push:
    branches: [ "ipod_touch_2g" ]
  pull_request:
    branches: [ "ipod_touch_2g" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Prerequisites
      run: sudo apt install make ninja-build pkg-config libssl-dev libsdl2-dev libpixman-1-dev libpixman-1-0 libglib2.0-dev
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
